### ISSUE TITLE
Feature: Add timer countdown + buttons

### ISSUE THREAD

**Issue by philipostli** [philipostli/com.uyunilighting#2]
- Add countdown on the device to track time left on the timer.
- Add buttons to trigger timer manually.
- Update on-off state when countdown is done.

**Comment by hmarkstrom** [comment]
I have bought one of  Nordic White Rustic Melted pillar UL-PI-NWM78010 and and two of Nordic Smooth Classic pillar UL-PI-MW-C78015 and Nordic Smooth Classic pillar UL-PI NW-C78020.  Nordic White Rustic Melted pillar UL-PI-NWM78010 Homey found immediately and when I tested it i also controlled Nordic Smooth Classic pillar UL-PI_MW-C78015 although I never have connected it to Homey. Nordic Smooth Classic pillar UL-PI NW-C78020 Homey have never found. I have no remote control. Didn't know that you needed one.

**Comment by philipostli** [comment]
Hey. It's probably better to use the [forums](https://community.homey.app/t/app-pro-uyuni-lighting/118286) for questions. I will add a link in the app store. 

The thing is you don't really add a device to Homey. You add a remote that resembles the one you can buy. It will work on all lights in near visinity of Homey. It is not possible to control them individually, even with the official remote. If one of the lights do not turn on I suspect it is because of distance from Homey or obstacles disturbing the line of sight. Infrared is vulnerable to physical objects, just as old TV remotes (before Bluetooth came along). 
You can also use the app in flows without adding a device. On/off should be visible as a action card.
Thanks for using the app☺️

**Comment by philipostli** [comment]
Pushed to test

**Comment by philipostli** [comment]
Added in 8305dc55fa6696b782a5245491409c449c537cc0
v1.2.0
